build:
  version: "2.0"

accounts:
  message: "Welcome to Eazybank accounts related QA APIs"
  contactDetails:
    name: "Smith Mary - QA Lead"
    email: "smithmary@eazybank.com"
  onCallSupport:
    - (555) 265-1234
    - (555) 734-1345