spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to Eazybank cards related QA APIs"
  contactDetails:
    name: "Smith Mary - QA Lead"
    email: "smithmary@eazybank.com"
  onCallSupport:
    - (555) 265-1234
    - (555) 734-1345